name: CI/CD using GitHub Actions & Docker

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker build & push to prod
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/plantify:0.0.1-SNAPSHOT .
          docker push ${{ secrets.DOCKER_USERNAME }}/plantify:0.0.1-SNAPSHOT

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter "name=qvick")
            if [ -n "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            sudo docker rmi -f ${{ secrets.DOCKER_USERNAME }}/plantify:0.0.1-SNAPSHOT

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/plantify:0.0.1-SNAPSHOT

            sudo docker run -d -p 8080:8080 --name qvick ${{ secrets.DOCKER_USERNAME }}/plantify:0.0.1-SNAPSHOT